### ISSUE TITLE
Missing Fork Button

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-inheritance-lab-pt-2#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195254?module_item_id=439037

### Concern

“Object Inheritance Lab, Part Two” doesn't have a fork button

**Comment by professor-ben** [comment]
Matt raised the same issue- just pushed a fix. This will be visible in the tech huddle course after the release of build 2.

Thanks!
-Ben
